// This file is generated by `actctl codegen`. Do not edit by hand.
// Re-run codegen after publishing a new class version.

/* eslint-disable */

export const MANIFEST_SHA = 'b57a639b74f10befb3231df58d3d25723519408cd65b2cebe60f08242cd926f4' as const;

// Cart@1.2.0 (sha256: 18e187a12389…)
export type CartState = { items: { sku: string; qty: number }[] };
export interface CartHandlers {
  addItem(args: { sku: string; qty: number }): Promise<{ total: number }>;
  clear(args: Record<string, never>): Promise<void>;
}

// Ledger@2.0.0 (sha256: 718303e09349…)
export type LedgerState = { balance: number };
export type LedgerEvent = { type: 'credit'; amount: number } | { type: 'debit'; amount: number };
export interface LedgerHandlers {
  credit(args: { amount: number }): Promise<LedgerEvent[]>;
}

export interface Classes {
  Cart: {
    state: CartState;
    event: never;
    handlers: CartHandlers;
    eventSourced: false;
  };
  Ledger: {
    state: LedgerState;
    event: LedgerEvent;
    handlers: LedgerHandlers;
    eventSourced: true;
  };
}

export type ClassName = keyof Classes;
