// This file is generated by `actctl codegen`. Do not edit by hand.
// ES reducer runtime — kept byte-identical to the server's reduce().

export const reducers = Object.freeze({
  Ledger: (state, event) => {
    if (event.type === 'credit') {
        return { balance: state.balance + event.amount };
    }
    return { balance: state.balance - event.amount };
},
});

export function applyEvent(className, state, event) {
  const r = reducers[className];
  if (!r) throw new Error(`no reducer for ${className}`);
  return r(state, event);
}
