/**
 * Emitter: takes a set of {@link ExtractedClass} records and turns
 * them into the three artifacts actctl writes to disk.
 *
 * - `index.d.ts`: per-class state type, ES event union, handler
 *   interface, a `Classes` umbrella interface, and the `MANIFEST_SHA`
 *   constant. The SDK consumes this for `client.actor('Cart').call.X`
 *   IntelliSense.
 *
 * - `manifest.json`: sha + resolved version map + per-class source
 *   shas. Suitable for committing alongside the .d.ts so consumers
 *   can byte-check the pinned manifest end-to-end.
 *
 * - `index.runtime.js`: ES reducer functions, one per ES class. The
 *   SDK imports this and dispatches `applyEvent(className, state, event)`
 *   so optimistic ES updates run byte-identically with the server.
 *
 * Output is deterministic: classes sorted by name, manifest entries
 * sorted by name, no timestamps in the body. The same input produces
 * byte-identical files across machines and runs.
 */
import ts from 'typescript';

import { manifestFromEntries, manifestSha256, type Manifest } from '../types/manifest.js';

import type { CodegenManifestJson, CodegenOutput, ExtractedClass } from './types.js';

const HEADER =
  '// This file is generated by `actctl codegen`. Do not edit by hand.\n' +
  '// Re-run codegen after publishing a new class version.\n';

export function emit(classes: readonly ExtractedClass[]): CodegenOutput {
  const sorted = [...classes].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  const manifestMap: Manifest = manifestFromEntries(sorted.map((c) => [c.name, c.version]));
  const manifestSha = manifestSha256(manifestMap);

  const perClassSha = new Map<string, string>();
  for (const c of sorted) perClassSha.set(c.name, c.sourceSha256);

  return {
    dts: emitDts(sorted, manifestSha),
    manifestJson: emitManifestJson(sorted, manifestSha),
    runtimeJs: emitRuntimeJs(sorted),
    manifestSha,
    perClassSha,
  };
}

/* ----------------------------------------------------- index.d.ts */

function emitDts(classes: readonly ExtractedClass[], manifestSha: string): string {
  const parts: string[] = [HEADER];
  parts.push(`/* eslint-disable */\n`);
  parts.push(`export const MANIFEST_SHA = '${manifestSha}' as const;\n`);

  for (const c of classes) {
    parts.push(blockForClass(c));
  }

  parts.push(umbrellaBlock(classes));
  return parts.join('\n');
}

function blockForClass(c: ExtractedClass): string {
  const headerLine = `// ${c.name}@${c.version} (sha256: ${c.sourceSha256.slice(0, 12)}…)`;
  const stateLine = `export type ${c.name}State = ${c.stateType};`;
  const eventLine = c.eventSourced ? `export type ${c.name}Event = ${c.eventType};\n` : '';
  const handlerLines: string[] = [];
  if (c.handlers.length === 0) {
    handlerLines.push('  // (no @handler methods declared)');
  } else {
    for (const h of c.handlers) {
      const ret = h.esEventReturn ? `${c.name}Event[]` : h.returnType;
      handlerLines.push(`  ${h.name}(args: ${h.argsType}): Promise<${ret}>;`);
    }
  }
  const handlerBlock = `export interface ${c.name}Handlers {\n${handlerLines.join('\n')}\n}`;
  return `${headerLine}\n${stateLine}\n${eventLine}${handlerBlock}\n`;
}

function umbrellaBlock(classes: readonly ExtractedClass[]): string {
  const lines: string[] = ['export interface Classes {'];
  for (const c of classes) {
    const ev = c.eventSourced ? `${c.name}Event` : 'never';
    lines.push(`  ${c.name}: {`);
    lines.push(`    state: ${c.name}State;`);
    lines.push(`    event: ${ev};`);
    lines.push(`    handlers: ${c.name}Handlers;`);
    lines.push(`    eventSourced: ${c.eventSourced ? 'true' : 'false'};`);
    lines.push(`  };`);
  }
  lines.push('}');
  lines.push('');
  lines.push('export type ClassName = keyof Classes;');
  return `${lines.join('\n')}\n`;
}

/* ------------------------------------------------- manifest.json */

function emitManifestJson(classes: readonly ExtractedClass[], manifestSha: string): string {
  const resolved: Record<string, string> = {};
  const sources: Record<string, string> = {};
  for (const c of classes) {
    resolved[c.name] = c.version;
    sources[c.name] = c.sourceSha256;
  }
  const body: CodegenManifestJson = {
    sha256: manifestSha,
    resolved,
    sources,
  };
  return JSON.stringify(body, null, 2);
}

/* --------------------------------------------- index.runtime.js */

function emitRuntimeJs(classes: readonly ExtractedClass[]): string {
  const esClasses = classes.filter((c) => c.eventSourced && c.reduceBody && c.reduceParams);
  const lines: string[] = [
    '// This file is generated by `actctl codegen`. Do not edit by hand.',
    "// ES reducer runtime — kept byte-identical to the server's reduce().",
    '',
    'export const reducers = Object.freeze({',
  ];
  for (const c of esClasses) {
    const { state, event } = c.reduceParams!;
    const jsBody = transpileReduceBody(c.name, state, event, c.reduceBody!);
    lines.push(`  ${c.name}: ${jsBody},`);
  }
  lines.push('});');
  lines.push('');
  lines.push('export function applyEvent(className, state, event) {');
  lines.push('  const r = reducers[className];');
  lines.push('  if (!r) throw new Error(`no reducer for ${className}`);');
  lines.push('  return r(state, event);');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

/**
 * Transpile a TS `reduce` method body to JS.
 *
 * Strategy: wrap the body in a top-level arrow function declaration,
 * run `ts.transpileModule` to strip type annotations, then pull the
 * arrow back out. This relies only on TS's own syntactic transpile —
 * no type checker — so it's deterministic and as portable as the
 * authoring constraints allow.
 *
 * Reducers that use TS-only features TS can't transpile (decorators,
 * enums, namespaces) produce a clear error; the user fixes the
 * reducer or the codegen output for that class is omitted.
 */
function transpileReduceBody(
  className: string,
  stateParam: string,
  eventParam: string,
  body: string,
): string {
  const wrapped = `const __reduce__ = (${stateParam}, ${eventParam}) => ${body};`;
  const out = ts.transpileModule(wrapped, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      removeComments: true,
      noEmitHelpers: true,
      isolatedModules: true,
    },
    reportDiagnostics: false,
  });
  const text = out.outputText.trim();
  // The transpile output ends with `;` and may include `export {};`.
  // Extract the arrow expression literally.
  const m = /const\s+__reduce__\s*=\s*([\s\S]+?);\s*(?:export\s*\{\s*\};?)?\s*$/.exec(text);
  if (!m) {
    throw new Error(`failed to transpile reduce body for ${className}`);
  }
  return m[1]!.trim();
}
