/**
 * `Client` — the top-level entry point of `@actjs/client`.
 *
 * One Client owns:
 *   - one WebSocket {@link Transport};
 *   - one {@link RpcClient} multiplexing all calls/subscribes;
 *   - one {@link SubscriptionState} applying inbound notifications;
 *   - one offline {@link OfflineQueueBackend} for mutations issued
 *     while disconnected.
 *
 * Public surface: `client.actor(class, id)` returns an
 * {@link ActorHandle} with `call`, `get`, `subscribe`, and
 * `optimistic`. The handle's `call.<method>` proxy is duck-typed at
 * runtime; the SDK relies on the codegen'd `Classes` umbrella for
 * compile-time safety.
 */
import { applyPatches, enablePatches, produceWithPatches, type Patch } from 'immer';

import type { ActorEventNotification } from '../wire/index.js';

import {
  makeOfflineQueue,
  type OfflineQueueBackend,
  type OfflineQueueMode,
  type QueuedCall,
} from './offline-queue.js';
import { RpcClient, RpcError } from './rpc.js';
import { SubscriptionState, type EsReducer, type SubscriptionListener } from './subscriptions.js';
import { Transport, type TransportOptions } from './transport.js';

enablePatches();

/* -------------------------------------------------------- Public types */

export type ManifestPin = string | 'latest';

export interface ClientWarning {
  readonly type: 'manifest-deprecated' | 'transport-reconnecting';
  readonly message: string;
  readonly attempt?: number;
  readonly delayMs?: number;
}

export interface ClientOptions {
  /** Base URL of the actjs server, e.g. `https://api.example.com`. */
  readonly url: string;
  /** Bearer token sent on REST/WS auth headers (when supported by host). */
  readonly token?: string;
  /** Manifest pin sent as `X-Actjs-Manifest`. Defaults to `'latest'`. */
  readonly pin?: ManifestPin;
  /** Offline queue mode. Default `'memory'`. */
  readonly offlineQueue?: OfflineQueueMode;
  /** Reducer map for ES actors, generated by `actctl codegen`. */
  readonly reducers?: Readonly<Record<string, EsReducer>>;
  /** Test seam: WebSocket constructor (`ws` package in Node). */
  readonly wsCtor?: TransportOptions['wsCtor'];
  /** Test seam: random source for backoff jitter. */
  readonly random?: () => number;
  /** Auto-connect on construction. Default true. */
  readonly autoConnect?: boolean;
  /** Listener fired for transport / manifest warnings. */
  readonly onWarning?: (w: ClientWarning) => void;
  /** Fired when an offline mutation is dropped after a 4xx. */
  readonly onMutationFailed?: (call: QueuedCall, err: unknown) => void;
}

export interface CallOptions {
  /** Override the idempotency key (default: random). */
  readonly idempotencyKey?: string;
  /**
   * When true (default for `optimistic` callers), the call is added
   * to the offline queue if the transport isn't open.
   */
  readonly enqueueWhenOffline?: boolean;
}

export interface SubscribeOptions {
  /** Pass the last seen seq to ask for ES replay. */
  readonly fromSeq?: bigint | string;
}

/* ----------------------------------------------------- ActorHandle */

export type CallMap = Record<string, (...args: unknown[]) => Promise<unknown>>;

export interface ActorHandle<C extends CallMap = CallMap, S = unknown> {
  readonly class: string;
  readonly id: string;
  /** Typed by the codegen'd `<Class>Handlers`. */
  readonly call: C;
  /** Same surface as `call` but optimized for read-only intent. */
  readonly get: C;
  subscribe(listener: SubscriptionListener<S>, options?: SubscribeOptions): Promise<() => void>;
  optimistic(mutator: (draft: S) => void, options?: CallOptions): Promise<void>;
}

/* ----------------------------------------------------------- Client */

export class Client {
  private readonly url: string;
  private readonly token: string | undefined;
  private readonly transport: Transport;
  private readonly rpc: RpcClient;
  private readonly subs = new SubscriptionState();
  private readonly offlineQueue: OfflineQueueBackend;
  private readonly reducers: Readonly<Record<string, EsReducer>>;
  private pin: ManifestPin;
  private readonly onWarning?: (w: ClientWarning) => void;
  private readonly onMutationFailed?: (call: QueuedCall, err: unknown) => void;
  /** Last-seq per (class:id) for ES replay on reconnect. */
  private readonly lastSeq = new Map<string, bigint>();
  /** Active subscriptions by `${class}:${id}` so we can re-issue on reconnect. */
  private readonly activeSubs = new Map<
    string,
    { className: string; actorId: string; subscriptionId: string }
  >();
  /** Calls currently in flight by Idempotency-Key. */
  private readonly inflight = new Map<string, QueuedCall>();
  private destroyed = false;

  constructor(options: ClientOptions) {
    this.url = options.url;
    if (options.token !== undefined) this.token = options.token;
    this.pin = options.pin ?? 'latest';
    this.reducers = options.reducers ?? {};
    this.offlineQueue = makeOfflineQueue(options.offlineQueue ?? 'memory');
    if (options.onWarning) this.onWarning = options.onWarning;
    if (options.onMutationFailed) this.onMutationFailed = options.onMutationFailed;

    this.transport = new Transport({
      url: this.wsUrl(),
      onMessage: (text) => this.rpc.ingest(text),
      onOpen: () => this.handleOpen(),
      onClose: () => this.handleClose(),
      onReconnectScheduled: (delayMs, attempt) => {
        this.onWarning?.({
          type: 'transport-reconnecting',
          message: `transport reconnecting in ${delayMs}ms (attempt ${attempt})`,
          attempt,
          delayMs,
        });
      },
      ...(options.wsCtor ? { wsCtor: options.wsCtor } : {}),
      ...(options.random ? { random: options.random } : {}),
    });
    this.rpc = new RpcClient(this.transport);
    this.rpc.on('actor.event', (params) => {
      this.handleActorEvent(params as ActorEventNotification);
    });

    if (options.autoConnect !== false) this.transport.connect();
  }

  /** Convenience: REST base URL (the constructor URL). */
  baseUrl(): string {
    return this.url;
  }

  /** Resolved manifest pin sent on every call. */
  manifestPin(): ManifestPin {
    return this.pin;
  }

  setManifestPin(pin: ManifestPin): void {
    this.pin = pin;
  }

  /** Build an ActorHandle. The proxy is duck-typed at runtime. */
  actor<C extends CallMap = CallMap, S = unknown>(
    className: string,
    id: string,
  ): ActorHandle<C, S> {
    const callProxy = new Proxy(
      {},
      {
        get: (_target, prop) => {
          if (typeof prop !== 'string') return undefined;
          return (args: unknown, opts?: CallOptions) => this.call(className, id, prop, args, opts);
        },
      },
    ) as C;
    return {
      class: className,
      id,
      call: callProxy,
      get: callProxy,
      subscribe: (listener, options) => this.subscribe(className, id, listener, options),
      optimistic: (mutator, opts) => this.optimistic(className, id, mutator, opts),
    } as ActorHandle<C, S>;
  }

  /** Tear down the transport + drop pending. */
  async close(): Promise<void> {
    if (this.destroyed) return;
    this.destroyed = true;
    this.transport.destroy();
    this.rpc.rejectAll(new Error('client closed'));
    this.subs.clear();
  }

  /* ----------------------------------- internal: handlers */

  private wsUrl(): string {
    // Translate `http(s)://` to `ws(s)://` for the WS endpoint.
    const u = new URL(this.url);
    u.protocol = u.protocol.replace(/^http/, 'ws');
    if (!u.pathname.endsWith('/')) u.pathname += '/';
    u.pathname += 'v1/ws';
    // The server reads the manifest pin from headers; WS doesn't have
    // arbitrary headers from browsers, so we pass it as a query
    // parameter on the connect URL. `'latest'` means "no pin" — the
    // server treats absence as "resolve fresh each request".
    if (this.pin !== 'latest') u.searchParams.set('manifest', this.pin);
    if (this.token) u.searchParams.set('token', this.token);
    return u.toString();
  }

  private async handleOpen(): Promise<void> {
    this.rpc.handleOpen();
    // Re-establish subscriptions: ES sends `fromSeq` so the server
    // replays exactly. SWM gets a fresh snapshot.
    for (const [key, info] of this.activeSubs) {
      try {
        const result = await this.rpc.request('actor.subscribe', {
          class: info.className,
          id: info.actorId,
        });
        info.subscriptionId = (result as { subscriptionId: string }).subscriptionId;
        this.activeSubs.set(key, info);
      } catch {
        // best effort; remain in activeSubs so a later reconnect tries again
      }
    }
    // Drain the offline queue in FIFO order.
    void this.drainOfflineQueue();
  }

  private handleClose(): void {
    this.rpc.handleClose();
  }

  private handleActorEvent(notification: ActorEventNotification): void {
    this.subs.apply(notification);
    if (notification.seq !== undefined) {
      try {
        const next = BigInt(notification.seq);
        // We don't know the (class, id) directly from the notification —
        // look up via activeSubs.
        for (const [key, info] of this.activeSubs) {
          if (info.subscriptionId === notification.subscriptionId) {
            this.lastSeq.set(key, next);
            break;
          }
        }
      } catch {
        // ignore
      }
    }
  }

  /* ----------------------------------- internal: call path */

  private async call(
    className: string,
    actorId: string,
    method: string,
    args: unknown,
    options?: CallOptions,
  ): Promise<unknown> {
    const idempotencyKey = options?.idempotencyKey ?? generateIdempotencyKey();
    const enqueueWhenOffline = options?.enqueueWhenOffline ?? false;
    const call: QueuedCall = {
      idempotencyKey,
      className,
      actorId,
      method,
      args,
      enqueuedAt: Date.now(),
    };
    if (this.transport.getState() !== 'open' && enqueueWhenOffline) {
      await this.offlineQueue.enqueue(call);
    }
    this.inflight.set(idempotencyKey, call);
    try {
      const result = await this.rpc.request('actor.call', {
        class: className,
        id: actorId,
        method,
        args,
      });
      return (result as { result: unknown }).result;
    } catch (err) {
      if (this.isPermanentFailure(err)) {
        await this.offlineQueue.remove(idempotencyKey).catch(() => undefined);
        this.onMutationFailed?.(call, err);
      }
      throw err;
    } finally {
      this.inflight.delete(idempotencyKey);
      await this.offlineQueue.remove(idempotencyKey).catch(() => undefined);
    }
  }

  private async drainOfflineQueue(): Promise<void> {
    const queued = await this.offlineQueue.list().catch(() => []);
    for (const call of queued) {
      try {
        await this.rpc.request('actor.call', {
          class: call.className,
          id: call.actorId,
          method: call.method,
          args: call.args,
        });
        await this.offlineQueue.remove(call.idempotencyKey).catch(() => undefined);
      } catch (err) {
        if (this.isPermanentFailure(err)) {
          await this.offlineQueue.remove(call.idempotencyKey).catch(() => undefined);
          this.onMutationFailed?.(call, err);
        } else {
          // Transient — leave the entry in the queue for the next
          // reconnect.
          break;
        }
      }
    }
  }

  private isPermanentFailure(err: unknown): boolean {
    if (!(err instanceof RpcError)) return false;
    // The server returns a problem-detail-shaped `data` blob with a
    // code; SubscriberLimit / MailboxFull / 408-ish errors are
    // retryable. Everything else we treat as permanent.
    const code = err.frameworkCode;
    if (!code) return false;
    return !RETRYABLE_FRAMEWORK_CODES.has(code);
  }

  /* ---------------------------- internal: subscribe path */

  private async subscribe<S>(
    className: string,
    actorId: string,
    listener: SubscriptionListener<S>,
    _options?: SubscribeOptions,
  ): Promise<() => void> {
    const key = `${className}:${actorId}`;
    const result = (await this.rpc.request('actor.subscribe', {
      class: className,
      id: actorId,
    })) as { subscriptionId: string };
    const reducer = (this.reducers[className] ?? null) as EsReducer<S> | null;
    // Pre-register so any buffered notifications find a record;
    // hold a placeholder listener that we replace with the user's
    // listener before the flush actually happens by adding the
    // listener BEFORE register fires its flush — order matters.
    const rec = this.subs.preRegister<S, unknown>(result.subscriptionId, reducer);
    rec.listeners.add(listener);
    // Now flush any buffered notifications that arrived between RPC
    // dispatch and response.
    this.subs.flushBuffered(result.subscriptionId);
    this.activeSubs.set(key, {
      className,
      actorId,
      subscriptionId: result.subscriptionId,
    });
    return () => {
      rec.listeners.delete(listener);
      if (rec.listeners.size === 0) {
        this.subs.unregister(result.subscriptionId);
        this.activeSubs.delete(key);
        // Best-effort server-side unsubscribe.
        void this.rpc
          .request('actor.unsubscribe', { subscriptionId: result.subscriptionId })
          .catch(() => undefined);
      }
    };
  }

  /* ----------------------------- internal: optimistic */

  private async optimistic<S>(
    className: string,
    actorId: string,
    mutator: (draft: S) => void,
    options?: CallOptions,
  ): Promise<void> {
    // Find an active subscription for this actor to apply the
    // optimistic mutation against; if there isn't one, fall through
    // to a plain call (the mutation has nowhere to land locally).
    const key = `${className}:${actorId}`;
    const subInfo = this.activeSubs.get(key);
    if (!subInfo) {
      // No subscription; fire the call without local apply.
      await this.call(className, actorId, '__optimistic_call__', {}, options);
      return;
    }
    const rec = this.subs.get(subInfo.subscriptionId);
    if (!rec) throw new Error(`no subscription record for ${key}`);

    const [nextState, _patches, inverse] = produceWithPatches(
      rec.state as S,
      mutator as (draft: S) => void,
    );
    rec.state = nextState as unknown;
    for (const listener of rec.listeners) listener(rec.state as S);

    try {
      await this.call(className, actorId, '__optimistic_call__', {}, options);
    } catch (err) {
      // Revert by applying the inverse patches to the *current* state —
      // not the state we forked from, since other updates may have
      // committed in the meantime.
      try {
        const reverted = applyPatches(rec.state as object, inverse as Patch[]) as unknown as S;
        rec.state = reverted as unknown;
        for (const listener of rec.listeners) listener(rec.state as S);
      } catch {
        // If the inverse no longer applies (state drifted), drop the
        // optimistic update and let the next server snapshot reconcile.
      }
      throw err;
    }
  }
}

const RETRYABLE_FRAMEWORK_CODES = new Set(['MailboxFull', 'SubscriberLimit']);

function generateIdempotencyKey(): string {
  // 128-bit random hex; same shape as UUIDs but doesn't require the
  // crypto.randomUUID() API (some old Safari builds lack it).
  const buf = new Uint8Array(16);
  const c = (globalThis as { crypto?: { getRandomValues?: (b: Uint8Array) => void } }).crypto;
  if (c?.getRandomValues) {
    c.getRandomValues(buf);
  } else {
    for (let i = 0; i < buf.length; i++) buf[i] = Math.floor(Math.random() * 256);
  }
  let s = '';
  for (const b of buf) s += b.toString(16).padStart(2, '0');
  return s;
}

/** Re-export so SDK consumers can `instanceof RpcError`. */
export { RpcError };
